FROM python:3.12-slim

WORKDIR /mlflow

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir "mlflow==3.15.1"

EXPOSE 5000

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:////mlflow/mlflow.db", "--default-artifact-root", "/mlflow/artifacts"]
